extensions:
  zpages:
    endpoint: 0.0.0.0:55679
  basicauth/client:
    client_auth:
      username: username
      password: password

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  syslog/bsd:
    protocol: rfc3164
    udp:
      listen_address: 0.0.0.0:514
  filelog:
    include: /var/log/messages
  journald:
    directory: /run/log/journal
    units:
      - ssh
    priority: info

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 512
  batch:
  attributes:
    actions:
      - key: test
        action: delete
  resource:
    attributes:
      - key: host.name
        value: example
        action: insert

exporters:
  loki:
    endpoint: https://loki.example.com:3100/loki/api/v1/push
  debug:
    verbosity: detailed

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
    logs/remote:
      receivers: [otlp, syslog/bsd]
      processors: [memory_limiter, batch]
      exporters: [debug]
    logs/local:
      receivers: [filelog, journald]
      processors:
        - memory_limiter
        - batch
      exporters: [debug]
