extensions:
  zpages:
    endpoint: 0.0.0.0:55679
  basicauth/client:
    client_auth:
      username: username
      password: password

connectors:
  forward:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  syslog/bsd:
    protocol: rfc3164
    udp:
      listen_address: 0.0.0.0:514
  filelog:
    include: /var/log/messages
  journald:
    directory: /run/log/journal
    units:
      - ssh
    priority: info
  hostmetrics:
    scrapers:
      cpu:
  prometheus:
    config:
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets: ["prometheus:9090"]
  podman_stats:
    endpoint: unix://var/run/podman/podman.sock

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 512
  batch:
  resource:
    attributes:
      - key: host.name
        value: example
        action: insert
  transform:

exporters:
  nop:
  debug:
    verbosity: detailed
  otlp:
    endpoint: injest.otlp.example.com:443
  otlphttp:
    endpoint: http://otlphttp.exampe.com

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp, hostmetrics, prometheus, podman_stats]
      processors: [memory_limiter, batch]
      exporters: [debug]
    logs/remote:
      receivers: [otlp, syslog/bsd]
      processors: [memory_limiter, batch]
      exporters: [debug]
    logs/local:
      receivers: [filelog, journald]
      processors:
        - memory_limiter
        - batch
      exporters: [debug]
