VERSION 0.8

IMPORT ../ AS common

ARG --global BASE_DIR = ./router/
ARG --global TAG_PREFIX = router-

build-image-all-platforms:
    BUILD --pass-args common+build-image-all-platforms
test-all-platforms:
    BUILD --pass-args common+test-all-platforms
build-image:
    BUILD --pass-args common+build-image
test:
    BUILD --pass-args common+test
