VERSION --arg-scope-and-set 0.7
ARG --global bird_version=2.13.1

all:
  BUILD --platform=linux/amd64 --platform=linux/arm64 +container
  BUILD --platform=linux/mips +bin-debian --distro=stretch

src:
  ARG USERPLATFORM
  FROM --platform=$USERPLATFORM curlimages/curl:8.2.1
  WORKDIR /work
  RUN curl -s -O https://bird.network.cz/download/bird-${bird_version}.tar.gz && \
    tar -xzf bird-${bird_version}.tar.gz && mv bird-${bird_version} bird
  SAVE ARTIFACT bird

bin-debian:
  ARG USERPLATFORM
  ARG USERARCH
  ARG TARGETARCH
  ARG distro=bookworm
  FROM --platform=$USERPLATFORM debian:${distro}-slim

  IF [ "${TARGETARCH}" = "amd64" ]
    LET host=x86_64-linux-gnu
    LET gcc=gcc-x86-64-linux-gnu
    ENV CC=x86_64-linux-gnu-gcc
  ELSE IF [ "${TARGETARCH}" = "arm64" ]
    LET host=aarch64-linux-gnu
    LET gcc=gcc-aarch64-linux-gnu
    ENV CC=aarch64-linux-gnu-gcc
  ELSE IF [ "${TARGETARCH}" = "mips" ]
    LET host=mips-linux-gnu
    LET gcc=gcc-mips-linux-gnu
    ENV CC=mips-linux-gnu-gcc
  END

  LET archlist=${USERARCH}
  IF [ "${TARGETARCH}" != "${USERARCH}" ]
    SET archlist="${USERARCH},${TARGETARCH}"
  END

  LET apt_sources=/etc/apt/sources.list.d/debian.sources
  IF [ "${distro}" = "stretch" ]
    # use archive repository for stretch
    SET apt_sources=/etc/apt/sources.list
    COPY stretch-sources.list /etc/apt/sources.list
  END

  RUN \
    dpkg --add-architecture ${TARGETARCH} && \
    sed -i "s/^deb /deb [arch=${archlist}] /" ${apt_sources} && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      make \
      iproute2 \
      flex \
      bison \
      libncurses5-dev:${TARGETARCH} \
      libreadline-dev:${TARGETARCH} \
      ${gcc}
  
  COPY +src/bird /work/bird
  WORKDIR /work/bird

  RUN ./configure \
        --host=${host} \
        --prefix=/usr/local/bird \
        --sysconfdir=/etc/bird \
        --with-runtimedir=/run/bird \
        --with-protocols="bgp,rpki,bfd,pipe,static" && \
        make && \
        make install
  
  SAVE ARTIFACT /usr/local/bird/sbin bin AS LOCAL ./bin

container: 
  ARG distro=bookworm
  ARG image_name=ghcr.io/tosuke-homelab/bird:${distro}-${bird_version}
  FROM debian:${distro}-slim

  RUN apt-get update && \
      apt-get install -y \
        iproute2 \
        libreadline8 && \
      rm -rf /var/lib/apt/lists/*
  
  COPY (+bin-debian/bin --distro=${distro}) /usr/local/bird/sbin

  ENV PATH=/usr/local/bird/sbin:$PATH
  ENTRYPOINT [ "/usr/local/bird/sbin/bird", "-f" ]
  SAVE IMAGE --push ${image_name}

