name: On pull request sync

on:
  pull_request:
    paths:
      - otelcol/**
      - .github/workflows/**

jobs:
  build_otelcol:
    uses: ./.github/workflows/wf-build-otelcol.yaml
    with:
      push: true
