name: On sync

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      result: ${{ steps.script.outputs.result }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7
        with:
          files_yaml: |
            workflows: [.github/workflows/**/*]
            bird: [bird/**/*]
            otelcol: [otelcol/**/*]
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: script
        env:
          changes: ${{ toJSON(steps.changes.outputs)}}
        with:
          script: |
            const { changed_keys = "" } = JSON.parse(process.env.changes)
            return {
              build: {
                otelcol: changed_keys.includes("workflows") || changed_keys.includes("otelcol"),
                bird: changed_keys.includes("workflows") || changed_keys.includes("bird"),
              },
            }
  build-otelcol:
    needs: [prepare]
    if: ${{ fromJSON(needs.prepare.outputs.result).build.otelcol }}
    uses: ./.github/workflows/wf-build-otelcol.yaml
    with:
      push: true
  build-bird:
    needs: [prepare]
    if: ${{ fromJSON(needs.prepare.outputs.result).build.bird }}
    uses: ./.github/workflows/wf-build-bird.yaml
    with:
      push: ${{ fromJSON(needs.prepare.outputs.push) }}
