name: On sync

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      build-otelcol: ${{ steps.changed.outputs.workflows_any_changed || steps.changed.outputs.otelcol_any_changed }}
      build-bird: ${{ steps.changed.outputs.workflows_any_changed || steps.changed.outputs.bird_any_changed }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45.0.2
        with:
          files_yaml: |
            workflows: [.github/workflows/**/*]
            bird: [bird/**/*]
            otelcol: [otelcol/**/*]
  build-otelcol:
    needs: [prepare]
    if: ${{ fromJSON(needs.prepare.outputs.build-otelcol) }}
    uses: ./.github/workflows/wf-build-otelcol.yaml
    with:
      push: true
  build-bird:
    needs: [prepare]
    if: ${{ fromJSON(needs.prepare.outputs.build-bird)}}
    uses: ./.github/workflows/wf-build-bird.yaml
    with:
      push: ${{ fromJSON(needs.prepare.outputs.push) }}
